version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    restart: always  
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - back_network
  api:
    build: 
      context: ./api
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      FRONT_DOMAIN: "localhost:$FRONT_PORT"
      API_URL: "http://localhost:$API_PORT"   
    volumes:
      - ./api:/$WORKDIR
      - gem_data:/usr/local/bundle
    ports:
      - "$API_PORT:$CONTAINER_PORT"
    depends_on:
      - db
    stdin_open: true
    tty: true
    networks: 
      - back_network
      - front_network
    
  front:
    build: 
      context: ./front
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: "http://localhost:$API_PORT"
    command: yarn run dev
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    volumes:
      - ./front:/$WORKDIR
    depends_on:
      - api
    tty: true
    networks:
      - front_network
volumes:
  mysql-data:
  gem_data:
networks:
  back_network:
    driver: bridge
  front_network:
    driver: bridge