FROM node:16.15.0-alpine

ARG WORKDIR
ARG CONTAINER_PORT
ARG API_URL

ENV HOME=/myapp \
    LANG=C.UTF-8 \
    TZ=Asia/Tokyo \
    HOST=0.0.0.0 \
    API_URL=${API_URL}

RUN mkdir myapp
WORKDIR myapp

COPY package.json .
COPY . .

EXPOSE ${CONTAINER_PORT}

CMD ["yarn", "start"]